.TH "CLEANPATH_FREE" "3" "" "" "API"
.SH NAME
cleanpath_free
.SH SYNOPSIS
\f[B]#include <cleanpath/cleanpath.h>\f[R]
.PP
\f[B]void cleanpath_free(struct CleanPath *\f[I]path\f[B])\f[R]
.PP
.SH DESCRIPTION
free a CleanPath pointer
.PP
.SH RETURNS
N/A
.PP
.SH CONFORMING TO
C99
.PP
.SH SEE ALSO
\f[B]cleanpath_init(3)\f[R],
\f[B]cleanpath_read(3)\f[R],
\f[B]cleanpath_free(3)\f[R]
.PP
